pip install requests --upgrade
pip install falcon --upgrade
pip install waitress --upgrade
pip install zodb --upgrade
pip install psycopg2 --upgrade
pip install psycogreen --upgrade
pip install gevent --upgrade
pip install RelStorage --upgrade
pip install RelStorage[postgresql] --upgrade
pip install zodburi --upgrade
pip install shortuuid --upgrade
pip install google-api-python-client --upgrade